import type {
  Customer,
  Product,
  Service,
  Employee,
  User,
  Role,
  Car,
} from "@/types";

// =============================================================================
// Mock Customers Data
// =============================================================================

export const mockCustomers: Customer[] = [
  {
    id: "1",
    name: "عبدالله أحمد الشمري",
    phone: "+966501234567",
    usageCount: 15,
    cars: [
      {
        id: "c1",
        name: "كامري",
        number: "أ ب ج 1234",
        model: "2023",
        color: "أبيض",
        customerId: "1",
        createdAt: new Date("2024-01-15"),
        updatedAt: new Date("2024-01-15"),
      },
      {
        id: "c2",
        name: "لاند كروزر",
        number: "س ص ع 5678",
        model: "2022",
        color: "أسود",
        customerId: "1",
        createdAt: new Date("2024-02-20"),
        updatedAt: new Date("2024-02-20"),
      },
    ],
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-06-20"),
  },
  {
    id: "2",
    name: "محمد سعود العتيبي",
    phone: "+966502345678",
    usageCount: 8,
    cars: [
      {
        id: "c3",
        name: "أكورد",
        number: "ه و ز 9012",
        model: "2024",
        color: "رمادي",
        customerId: "2",
        createdAt: new Date("2024-03-10"),
        updatedAt: new Date("2024-03-10"),
      },
    ],
    createdAt: new Date("2024-03-10"),
    updatedAt: new Date("2024-05-15"),
  },
  {
    id: "3",
    name: "فهد خالد القحطاني",
    phone: "+966503456789",
    usageCount: 22,
    cars: [
      {
        id: "c4",
        name: "باترول",
        number: "ط ي ك 3456",
        model: "2021",
        color: "فضي",
        customerId: "3",
        createdAt: new Date("2023-12-01"),
        updatedAt: new Date("2023-12-01"),
      },
    ],
    createdAt: new Date("2023-12-01"),
    updatedAt: new Date("2024-06-25"),
  },
  {
    id: "4",
    name: "سلطان عبدالرحمن الدوسري",
    phone: "+966504567890",
    usageCount: 5,
    cars: [
      {
        id: "c5",
        name: "سوناتا",
        number: "ل م ن 7890",
        model: "2023",
        color: "أزرق",
        customerId: "4",
        createdAt: new Date("2024-04-05"),
        updatedAt: new Date("2024-04-05"),
      },
    ],
    createdAt: new Date("2024-04-05"),
    updatedAt: new Date("2024-04-20"),
  },
  {
    id: "5",
    name: "عمر ناصر المالكي",
    phone: "+966505678901",
    usageCount: 12,
    cars: [
      {
        id: "c6",
        name: "افالون",
        number: "ع ف ص 1122",
        model: "2022",
        color: "بني",
        customerId: "5",
        createdAt: new Date("2024-02-01"),
        updatedAt: new Date("2024-02-01"),
      },
      {
        id: "c7",
        name: "يوكن",
        number: "ق ر س 3344",
        model: "2024",
        color: "أبيض لؤلؤي",
        customerId: "5",
        createdAt: new Date("2024-05-10"),
        updatedAt: new Date("2024-05-10"),
      },
    ],
    createdAt: new Date("2024-02-01"),
    updatedAt: new Date("2024-06-10"),
  },
];

// =============================================================================
// Mock Products Data
// =============================================================================

export const mockProducts: Product[] = [
  {
    id: "1",
    name: "زيت موتور موبيل 1",
    minPrice: 45,
    costPrice: 40,
    salePrice: 55,
    photos: [],
    unit: "liter",
    stock: 150,
    minStock: 20,
    barcode: "6291001234567",
    description: "زيت موتور صناعي بالكامل 5W-30",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-06-01"),
  },
  {
    id: "2",
    name: "فلتر زيت تويوتا",
    minPrice: 25,
    costPrice: 20,
    salePrice: 35,
    photos: [],
    unit: "piece",
    stock: 80,
    minStock: 15,
    barcode: "6291001234568",
    description: "فلتر زيت أصلي لسيارات تويوتا",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-05-15"),
  },
  {
    id: "3",
    name: "سائل تبريد أخضر",
    minPrice: 30,
    costPrice: 25,
    salePrice: 40,
    photos: [],
    unit: "liter",
    stock: 60,
    minStock: 10,
    barcode: "6291001234569",
    description: "سائل تبريد مركز عالي الجودة",
    createdAt: new Date("2024-02-01"),
    updatedAt: new Date("2024-04-20"),
  },
  {
    id: "4",
    name: "فلتر هواء يابس",
    minPrice: 35,
    costPrice: 30,
    salePrice: 50,
    photos: [],
    unit: "piece",
    stock: 5,
    minStock: 10,
    barcode: "6291001234570",
    description: "فلتر هواء للمحرك",
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-06-10"),
  },
  {
    id: "5",
    name: "زيت فرامل DOT4",
    minPrice: 20,
    costPrice: 15,
    salePrice: 28,
    photos: [],
    unit: "liter",
    stock: 40,
    minStock: 8,
    barcode: "6291001234571",
    description: "زيت فرامل عالي الأداء",
    createdAt: new Date("2024-03-01"),
    updatedAt: new Date("2024-05-25"),
  },
  {
    id: "6",
    name: "شمعات إشعال NGK",
    minPrice: 15,
    costPrice: 12,
    salePrice: 22,
    photos: [],
    unit: "piece",
    stock: 0,
    minStock: 20,
    barcode: "6291001234572",
    description: "شمعات إشعال يابانية",
    createdAt: new Date("2024-02-15"),
    updatedAt: new Date("2024-06-20"),
  },
];

// =============================================================================
// Mock Services Data
// =============================================================================

export const mockServices: Service[] = [
  {
    id: "1",
    name: "تغيير زيت المحرك",
    price: 80,
    icon: "Droplets",
    description: "تغيير زيت المحرك مع الفلتر",
    estimatedDuration: 30,
    isActive: true,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "2",
    name: "غسيل خارجي",
    price: 40,
    icon: "Car",
    description: "غسيل السيارة من الخارج",
    estimatedDuration: 20,
    isActive: true,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "3",
    name: "غسيل داخلي وخارجي",
    price: 80,
    icon: "Sparkles",
    description: "غسيل شامل للسيارة",
    estimatedDuration: 45,
    isActive: true,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "4",
    name: "تلميع السيارة",
    price: 150,
    icon: "Sun",
    description: "تلميع وتشميع السيارة",
    estimatedDuration: 90,
    isActive: true,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "5",
    name: "فحص شامل",
    price: 100,
    icon: "Search",
    description: "فحص شامل لجميع أجزاء السيارة",
    estimatedDuration: 60,
    isActive: true,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "6",
    name: "تغيير الإطارات",
    price: 60,
    icon: "Circle",
    description: "فك وتركيب الإطارات",
    estimatedDuration: 40,
    isActive: true,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "7",
    name: "شحن البطارية",
    price: 30,
    icon: "Battery",
    description: "شحن بطارية السيارة",
    estimatedDuration: 15,
    isActive: true,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "8",
    name: "صيانة المكيف",
    price: 120,
    icon: "Wind",
    description: "فحص وصيانة نظام التكييف",
    estimatedDuration: 60,
    isActive: false,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
];

// =============================================================================
// Mock Employees Data
// =============================================================================

export const mockEmployees: Employee[] = [
  {
    id: "1",
    name: "خالد عبدالعزيز",
    position: "manager",
    phone: "+966551234567",
    salary: 12000,
    hireDate: new Date("2022-01-15"),
    isActive: true,
    createdAt: new Date("2022-01-15"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "2",
    name: "سعيد محمد",
    position: "technician",
    phone: "+966552345678",
    salary: 6000,
    hireDate: new Date("2022-06-01"),
    isActive: true,
    createdAt: new Date("2022-06-01"),
    updatedAt: new Date("2024-02-01"),
  },
  {
    id: "3",
    name: "أحمد عمر",
    position: "technician",
    phone: "+966553456789",
    salary: 5500,
    hireDate: new Date("2023-01-10"),
    isActive: true,
    createdAt: new Date("2023-01-10"),
    updatedAt: new Date("2024-01-15"),
  },
  {
    id: "4",
    name: "ياسر علي",
    position: "receptionist",
    phone: "+966554567890",
    salary: 4500,
    hireDate: new Date("2023-03-20"),
    isActive: true,
    createdAt: new Date("2023-03-20"),
    updatedAt: new Date("2024-03-01"),
  },
  {
    id: "5",
    name: "فيصل سعد",
    position: "accountant",
    phone: "+966555678901",
    salary: 7000,
    hireDate: new Date("2022-09-01"),
    isActive: true,
    createdAt: new Date("2022-09-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "6",
    name: "عبدالرحمن حسن",
    position: "cleaner",
    phone: "+966556789012",
    salary: 3000,
    hireDate: new Date("2023-06-15"),
    isActive: false,
    createdAt: new Date("2023-06-15"),
    updatedAt: new Date("2024-05-01"),
  },
];

// =============================================================================
// Mock Roles Data
// =============================================================================

export const mockRoles: Role[] = [
  {
    id: "1",
    name: "مدير النظام",
    permissions: [
      { resource: "customers", level: "write" },
      { resource: "products", level: "write" },
      { resource: "services", level: "write" },
      { resource: "employees", level: "write" },
      { resource: "users", level: "write" },
      { resource: "reports", level: "write" },
    ],
  },
  {
    id: "2",
    name: "مدير المبيعات",
    permissions: [
      { resource: "customers", level: "write" },
      { resource: "products", level: "read" },
      { resource: "services", level: "read" },
      { resource: "employees", level: "none" },
      { resource: "users", level: "none" },
      { resource: "reports", level: "read" },
    ],
  },
  {
    id: "3",
    name: "كاشير",
    permissions: [
      { resource: "customers", level: "read" },
      { resource: "products", level: "read" },
      { resource: "services", level: "read" },
      { resource: "employees", level: "none" },
      { resource: "users", level: "none" },
      { resource: "reports", level: "none" },
    ],
  },
  {
    id: "4",
    name: "مشاهد فقط",
    permissions: [
      { resource: "customers", level: "read" },
      { resource: "products", level: "read" },
      { resource: "services", level: "read" },
      { resource: "employees", level: "read" },
      { resource: "users", level: "none" },
      { resource: "reports", level: "read" },
    ],
  },
];

// =============================================================================
// Mock Users Data
// =============================================================================

export const mockUsers: User[] = [
  {
    id: "1",
    name: "أحمد محمد",
    phone: "+966500000000",
    position: "admin",
    roles: [mockRoles[0]],
    isActive: true,
    lastLogin: new Date("2024-06-25T10:30:00"),
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-06-25"),
  },
  {
    id: "2",
    name: "سارة علي",
    phone: "+966500000001",
    position: "manager",
    roles: [mockRoles[1]],
    isActive: true,
    lastLogin: new Date("2024-06-24T14:20:00"),
    createdAt: new Date("2024-02-01"),
    updatedAt: new Date("2024-06-24"),
  },
  {
    id: "3",
    name: "محمود أحمد",
    phone: "+966500000002",
    position: "cashier",
    roles: [mockRoles[2]],
    isActive: true,
    lastLogin: new Date("2024-06-25T08:00:00"),
    createdAt: new Date("2024-03-15"),
    updatedAt: new Date("2024-06-25"),
  },
  {
    id: "4",
    name: "نورة سعود",
    phone: "+966500000003",
    position: "viewer",
    roles: [mockRoles[3]],
    isActive: false,
    createdAt: new Date("2024-04-01"),
    updatedAt: new Date("2024-05-15"),
  },
];
